version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"  # React served by Nginx
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
